export const storeNfts = (set) => ({
  ProfileNft: [],
  ProfileNftActivity: [],
  PageExploreNft: [],
  TotalPageExploreNft: 0,
  PageExploreCollections: [],
  TotalPageExploreCollections: 0,
  PageExploreUser: [],
  TotalPageExploreUser: 0,
  PageActivity: [],
  TotalPageActivity: 0,
  PageActivityFilter: "All",
  PageNfts: [],
  TotalPageNfts: 0,
  PageNftsFilter: "All",
  ChangeProfileNft: (value) => set({ ProfileNft: value }),
  ChangeProfileNftActivity: (value) => set({ ProfileNftActivity: value }),
  ChangePageExploreNft: (value) => set({ PageExploreNft: value }),
  ChangeTotalPageExploreNft: (value) => set({ TotalPageExploreNft: value }),
  ChangePageExploreCollections: (value) =>
    set({ PageExploreCollections: value }),
  ChangeTotalPageExploreCollections: (value) =>
    set({ TotalPageExploreCollections: value }),
  ChangePageExploreUsers: (value) => set({ PageExploreUser: value }),
  ChangeTotalPageExploreUsers: (value) => set({ TotalPageExploreUser: value }),
  ChangePageActivity: (value) => set({ PageActivity: value }),
  ChangePageActivityFilter: (value) => set({ PageActivityFilter: value }),
  ChangeTotalPageActivity: (value) => set({ TotalPageActivity: value }),
  ChangePageNfts: (value) => set({ PageNfts: value }),
  ChangeTotalPageNfts: (value) => set({ TotalPageNfts: value }),
  ChangePageNftsFilter: (value) => set({ PageNftsFilter: value }),
});
